### PR TITLE
Do not force boost filesystem no deprecated

### PR DESCRIPTION
**Pull request by bvbfan**
Forcing BOOST_FILESYSTEM_NO_DEPRECATED makes no sense in source. It can added to configure by CCFLAGS.
Fix build with Boost > 1.74

### CODE REVIEW

**Comment by ShengguangXiao** [comment]
What's the compile error if boost version > 1.74?

**Comment by Bushstar** [comment]
@ShengguangXiao here's the upstream change.

https://github.com/bitcoin/bitcoin/commit/a64e97dd476bda7c7981979d045b0d06d6f7ce47#diff-3492213c413b2d41f5e11a676db8f69ff54f71a2f5a14b2f61ee919d3a9f5122

From the above commit text.

```
wallet/walletutil.cpp:77:23: error: no member named 'level' in 'boost::filesystem::recursive_directory_iterator'
        } else if (it.level() == 0 && it->symlink_status().type() == fs::regular_file && IsBerkeleyBtree(it...
                   ~~ ^
```

@bvbfan Personally I like to see a cherry-pick of upstream changes.

**Comment by bvbfan** [comment]
Also `copy_option` is deprecated and renamed to `copy_options` to match stdc++17 one.

**Comment by bvbfan** [comment]
cherry-picked

**Comment by ShengguangXiao** [comment]
Actually i have fixed this issue before, don't know why it comes back.
https://github.com/DeFiCh/ain/pull/26

**Comment by bvbfan** [comment]
@ShengguangXiao the issue is different here
`fs::copy_file(pathSrc, pathDest, fs::copy_option::overwrite_if_exists);`
It does not compile since `copy_option` is deprecated i wrote it above.

**Comment by ShengguangXiao** [comment]
@bvbfan You can fix the compile issue with new boost like below. Eventually there will be one day we also need to upgrade C++ and boost, so we should adopt new definitions.
https://github.com/Icinga/icinga2/pull/8184/files

**Comment by Bushstar** [comment]
@ShengguangXiao I would rather we follow upstream solutions from Bitcoin, the fix applied here is a cherry-pick from Bitcoin.

**Comment by bvbfan** [comment]
@ShengguangXiao also forcing definition in header/source file does not look right. It should be done via configure CPPFLAGS.

**Comment by ShengguangXiao** [comment]
Ok, then should be good. We follow Bitcoin.

**Review by ShengguangXiao — APPROVED** [review]
